//
//  Airplane.swift
//  Airliners
//
//  Created by Nguyễn Minh Hiếu on 28/06/2021.
//

import Foundation

struct Airplane {
    var title : String?
    var model : String?
    var image : String?
    var shortInfor : String?
    var information : AirplaneInfor?
}


extension Airplane {
    static let example = [Airplane(title: "Boeing 787 Dreamliner", model: "787 Dreamliner", image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Boeing_787_N1015B_ANA_Airlines_%2827611880663%29_%28cropped%29.jpg", shortInfor: "Heavy, twin-engine, twin aisle, long-range widebody", information: AirplaneInfor(longDescription: "The Boeing 787 Dreamliner is an American long-haul, mid-size wide-body, twin-engine jet airliner manufactured by Boeing Commercial Airplanes. Its variants seat 242 to 330 passengers in typical two-class seating configurations. It is the first airliner with an airframe constructed primarily of composite materials. The 787 was designed to be 20% more fuel-efficient than the Boeing 767, which it was intended to replace. The 787 Dreamliner's distinguishing features include mostly electrical flight systems, raked wingtips, and noise-reducing chevrons on its engine nacelles.", nationalOrigin: "United States", manufacturer: "Boeing Commercial Airplanes", firstFlight: "December 15, 2009", produced: "2007–present", numberBuild: "1,005 as of May 2021", status: "In service")),
                          Airplane(title: "The Boeing 777", model: "777", image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Cathay_Pacific_Boeing_777-200%3B_B-HNL%40HKG.jpg", shortInfor: "Heavy, twin-engine, twin aisle, medium- to long-range, ultra long-range (200LR), widebody", information: AirplaneInfor(longDescription: "The Boeing 777 is a long-range wide-body twin-engine jet airliner developed and manufactured by Boeing Commercial Airplanes. It is the world's largest twinjet and has a typical seating capacity of 314 to 396 passengers, with a range of 5,240 to 8,555 nautical miles (9,704 to 15,844 km). Commonly referred to as the Triple Seven, its distinguishing features include large-diameter turbofan engines, long raked wings, six wheels on each main landing gear, fully circular fuselage cross-section, and a blade-shaped tail cone. Developed in consultation with eight major airlines, the 777 was designed to replace older wide-body airliners and bridge the capacity difference between Boeing's 767 and 747. As Boeing's first fly-by-wire airliner, it has computer-mediated controls. It was also the first commercial aircraft to be designed entirely with computer-aided design.", nationalOrigin: "United States", manufacturer: "Boeing Commercial Airplanes", firstFlight: "June 12, 1994", produced: "1993–present", numberBuild: "1,662 as of May 2021", status: "In service")),
                          Airplane(title: "The Boeing 767", model: "767", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Delta_Air_Lines_B767-332_N130DL.jpg/1920px-Delta_Air_Lines_B767-332_N130DL.jpg", shortInfor: "Heavy, twin-engine, twin aisle, medium- to long-range widebody", information: AirplaneInfor(longDescription: "The Boeing 767 is a mid- to large-size, mid- to long-range, wide-body twin-engine jet airliner developed and manufactured by Boeing Commercial Airplanes. It was Boeing's first wide-body twinjet and its first airliner with a two-crew glass cockpit. The aircraft has two turbofan engines, a conventional tail, and, for reduced aerodynamic drag, a supercritical wing design. Designed as a smaller wide-body airliner than earlier aircraft such as the 747, the 767 has a seating capacity for 181 to 375 people, and a design range of 3,850 to 6,385 nautical miles (4,431 to 7,348 mi; 7,130 to 11,825 km), depending on variant. Development of the 767 occurred in tandem with a narrow-body twinjet, the 757, resulting in shared design features which allow pilots to obtain a common type rating to operate both aircraft.", nationalOrigin: "United States", manufacturer: "Boeing Commercial Airplanes", firstFlight: "September 26, 1981", produced: "1981–present", numberBuild: "1,215 as of May 2021", status: "In service")),
                          Airplane(title: "The Boeing 757", model: "757", image: "https://upload.wikimedia.org/wikipedia/commons/3/31/Icelandair_Boeing_757-200_Wedelstaedt.jpg", shortInfor: "Mid-sized, narrow-body short to medium range, twin-engine", information: AirplaneInfor(longDescription: "The Boeing 757 is a mid-sized, narrow-body short to medium range, twin-engine airliner that was designed and built by Boeing Commercial Airplanes. It is the manufacturer's largest single-aisle passenger aircraft and was produced from 1981 to 2004. The twinjet has a two-crew member glass cockpit, turbofan engines of sufficient power to allow takeoffs from relatively short runways and higher altitudes, a conventional tail and, for reduced aerodynamic drag, a supercritical wing design. Intended to replace the smaller three-engine 727 on short and medium routes, the 757 can carry 200 to 295 passengers for a maximum of 3,150 to 4,100 nautical miles (5,830 to 7,590 km), depending on variant. The 757 was designed concurrently with a wide-body twinjet, the 767, and, owing to shared features, pilots can obtain a common type rating that allows them to operate both aircraft.", nationalOrigin: "United States", manufacturer: "Boeing Commercial Airplanes", firstFlight: "February 19, 1982", produced: "1981–2004", numberBuild: "1,050", status: "In service"))]
}

