# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Capstone_nqhuy9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Capstone_nqhuy9
  pod 'RxSwift', '5'
  pod 'RxCocoa', '5'
  pod 'RxGesture', '~> 3.0'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'


  target 'Capstone_nqhuy9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Capstone_nqhuy9UITests' do
    # Pods for testing
  end

end
