# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Capstone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Capstone
 

  target 'CapstoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapstoneUITests' do
    # Pods for testing
  end

end
